apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: testrtc-speedtest-app
spec:
  selector:
    matchLabels:
      app: speedtest
      tier: app
  replicas: {{ .Values.app.replicaCount}}
  template:
    metadata:
      labels:
        app: speedtest
        tier: app
    spec:
      containers:
      - name: nettest
        image: "{{ .Values.app.image.name }}:{{ .Values.app.image.tag }}"
        resources: {{ .Values.app.resources }}
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # Using `GET_HOSTS_FROM=dns` requires your cluster to
          # provide a dns service. As of Kubernetes 1.3, DNS is a built-in
          # service launched automatically. However, if the cluster you are using
          # does not have a built-in DNS service, you can instead
          # instead access an environment variable to find the master
          # service's host. To do so, comment out the 'value: dns' line above, and
          # uncomment the line below:
          # value: env
        - name: DOCKER_IMAGE_NAME
          value: {{ .Values.app.image.name }}
        - name: DOCKER_IMAGE_TAG
          value: {{ .Values.app.image.tag }}
        ports:
        - containerPort: {{ .Values.app.containerPort }}
