apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: testrtc-speedtest-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.app.ingress.staticIpName }}
  labels:
    app: speedtest
    tier: app
spec:
  backend:
    serviceName: testrtc-speedtest-service
    servicePort: {{ .Values.app.service.port }}