apiVersion: v1
kind: Service
metadata:
  name: app-backend
  labels:
    app: speedtest
    tier: app
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  # type: NodePort
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the app service.
  type: {{ .Values.app.service.type }}
  selector:
    app: speedtest
    tier: app
  ports:
  - port: {{ .Values.app.service.port }}
    targetPort: {{ .Values.app.service.targetPort }}
