apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: speedtest
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: speedtest
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: "{{ .Values.frontend.image.name }}:{{ .Values.frontend.image.tag }}"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # Using `GET_HOSTS_FROM=dns` requires your cluster to
          # provide a dns service. As of Kubernetes 1.3, DNS is a built-in
          # service launched automatically. However, if the cluster you are using
          # does not have a built-in DNS service, you can instead
          # instead access an environment variable to find the master
          # service's host. To do so, comment out the 'value: dns' line above, and
          # uncomment the line below:
          # value: env
        - name: DOCKER_IMAGE_NAME
          value: {{ .Values.frontend.image.name }}
        - name: DOCKER_IMAGE_TAG
          value: {{ .Values.frontend.image.tag }}
        ports:
        - containerPort: {{ .Values.frontend.containerPort }}
